### ISSUE TITLE
Product creation

### ISSUE THREAD

**Issue by abbeyjackson** [printdotio/gooten-ios-core#1]
@perisicboro Would it be possible to open up the SDK to be able to create products also?

I'm happy to help if needed, this is an integral feature for an app (my own hobby app) I am trying to build. I want to sell prints of my paintings and I would prefer to go through my own streamlined interface because:
a)  most of the options for each product will be the same so it would be faster than going through the Gooten hub
b) this way it is easy for me to continually add new products and manage them straight inside my app.

**Comment by perisicboro** [comment]
What do you mean by product creation? this ios core is only api wrapper.
you can take a look at https://github.com/printdotio/printio-ios-sdk

**Comment by abbeyjackson** [comment]
@perisicboro Thanks for replying quickly. When I logged into Gooten website, as a producer you have to go to the "hub" and click the "create"button to add a new product. If you do this it now shows up on the Simple Order Form as a "print ready product".

I may not quite understand the way your system works as I have never worked with a print on demand service before so bear with me if I am a bit confused (or confusing!).

My plan is to create an app which I would log into as the app owner and also customers would log into as customers. As the app owner I would manage the products that are for sale. My customers would be able to purchase those products. 

Essentially I want to be able to do everything via my own app and not have to log into the Gooten website when I want to make a new product available. 

So when I ask about creating new products, what I mean is I would like to be able to create a print ready product via the ios sdk.

Then I would additionally like to be able to present the print ready products that I created to my customers for them to purchase.

I have my own UI and would not need to use the UI in the ios sdk you gave a link to. Either way I do not see the term "print ready" in either the [ios core](https://github.com/printdotio/gooten-ios-core/blob/master/docs/gooten_core_sdk.md#getting-a-list-of-skus-product-variants-for-a-product) documentation nor the [ios sdk](https://github.com/printdotio/printio-ios-sdk/blob/master/docs/code_customization.md) documentation.

Is it possible to do what I am wanting to do?

**Comment by perisicboro** [comment]
@abbeyjackson At this moment, it's not possible to create PRP via iOS SDK. But we have API, that you could use in your iOS app, to create, get, remove and update PRP products.

https://www.gooten.com/platforms/api/documentation/print-ready-products/

**Comment by abbeyjackson** [comment]
@perisicboro fantastic!

Thank you for all your help and btw I really think you guys have done a really great job with your api's and platform specific libraries. Your set up and documentation is better than most tech specific companies' stuff.
